# Generated by Django 2.2.5 on 2019-10-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191014_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='src_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='src_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='src_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='src_5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='src',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
